app/Http/routes.php
<?php

Route::group(['middleware' => 'web'], function() {
    /**
     * Switch between the included languages
     */
    Route::group(['namespace' => 'Language'], function () {
        require (__DIR__ . '/Routes/Language/Language.php');
    });

    /**
     * Frontend Routes
     * Namespaces indicate folder structure
     */
    Route::group(['namespace' => 'Frontend'], function () {
        require (__DIR__ . '/Routes/Frontend/Frontend.php');
        require (__DIR__ . '/Routes/Frontend/Access.php');
    });
});

/**
 * Backend Routes
 * Namespaces indicate folder structure
 * Admin middleware groups web, auth, and routeNeedsPermission
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
    /**
     * These routes need view-backend permission
     * (good if you want to allow more than one group in the backend,
     * then limit the backend features by different roles or permissions)
     *
     * Note: Administrator has all permissions so you do not have to specify the administrator role everywhere.
     */
    require (__DIR__ . '/Routes/Backend/Dashboard.php');
    require (__DIR__ . '/Routes/Backend/Access.php');
    require (__DIR__ . '/Routes/Backend/LogViewer.php');
});







/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/

Route::group(['prefix' => 'api'], function ()
{
    Route::group(['prefix' => 'v1'], function ()
    {
        require config('infyom.laravel_generator.path.api_routes');
    });
});

app/Models/Tasks/Task.php
<?php

namespace App\Models\Tasks;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Access\User\User;
use Phoenix\EloquentMeta\MetaTrait;
use Carbon\Carbon;

class Task extends Model implements \MaddHatter\LaravelFullcalendar\Event
{
    use SoftDeletes, MetaTrait;
    protected $table = 'tasks';
    protected $dates = ['deleted_at','start', 'end'];

    public function service() {
      return $this->belongsTo('App\Models\Services\Service');
    }

    public function options() {
      return $this->service->metas;
    }

    public function customer() {
      return $this->belongsTo('App\Models\Customers\Customer');
    }

    public function order() {
      return $this->belongsTo('App\Models\Orders\Order');
    }

    public function notes_id() {
      return $this->order->notes_id;
    }

    public function files() {
      return $this->hasMany('App\Models\Media\File');
    }

    public function getCompanyCodeAttribute(){
      return $this->order->company->code;
    }

    public function getAssignNameAttribute(){
      $uids = explode(',',$this->assign_users);
      if(count($uids) > 1){
        $names = [];
        foreach ($uids as $uid) {
          $names[$uid] = User::find($uid)->name;
        }
        return $names;
      }elseif(count($uids) == 1 && !empty($uids[0])){
        $user = User::find($uids[0]);
        return [$uids[0] => $user->name];
      }else{
        return [];
      }
    }

    public function getResourceIdAttribute(){
      return $this->service->resourceId;
    }

    public function getDisplayNameAttribute(){
      return $this->service->display_name;
    }

    public function getAvaibleOptionsAttribute(){
      return json_encode($this->avaibleOptions());
    }

    public function getOrderRidAttribute(){
      return $this->order->rid;
    }

    public function allowUpload(){
      $avaibleOptions = $this->avaibleOptions();
      foreach ($avaibleOptions as $option) {
        if($option['type'] == 'submited'){
          return true;
        }
      }
      return false;
    }

    public function allowSchedule(){
      $avaibleOptions = $this->avaibleOptions();
      foreach ($avaibleOptions as $option) {
        if($option['type'] == 'schedule' || $option['type'] == 'reschedule'){
          return true;
        }
      }
      return false;
    }

    public function avaibleOptions(){
      $all = taskStatus($this->service->name);
      $allStatus = [];

      foreach ($all as $status) {
        $requireRoles = explode(',',$status['role']);
        if(access()->hasRoles($requireRoles, false) || access()->hasRole('Administrator')){
          $allStatus[] = ['type'=>$status['type']];
        }
      }

      return $allStatus;
    }


    public function gallery() {
      if($this->allowUpload()){
        $output= [];
        $files = $this->files;
        foreach ($files as $file) {
          $output[] = [
            'title' => $file->filename,
            'href' => $file->url(),
            'thumbnail' => $file->thumbnail(),
            'withlogo' => $file->withLogo()
          ];
        }
        return json_encode($output);
      }
      return json_encode([]);
    }

    public function galleryMobile() {
      $output= [];
      $files = $this->files;
      foreach ($files as $file) {
        $output[] = [
          'id' => $file->id,
          'thumbnail' => $file->thumbnail(),
          'url' => $file->withLogo()
        ];
      }
      return json_encode($output);
    }

    public function galleryDesktop() {
      $output= [];
      $files = $this->files;
      $picked = $this->getMeta('selected', false);
      foreach ($files as $file) {
        $output[] = [
          'id' => $file->id,
          'thumbnail' => $file->thumbnail(),
          'src' => $file->url(),
          'selected' => $picked ? in_array($file->id, $picked) : false
        ];

      }
      return $output;
    }

    public function getColor() {
      switch ($this->type) {
        case 'pre-photoshot':
          $pretype = $this->getMeta('op-Type');
          if($pretype){
            if($pretype == 'Outdoor'){
              return '#4986E7';
            }elseif($pretype == 'Studio'){
              return '#16A765';
            }else{
              return '#9FE1E7';
            }
          }else{
            return '#9FE1E7';
          }
          return '#7FDBFF';
          break;

        case 'wd-photoshot':
          return '#0074D9';
          break;

        default:
          return '#111111';
          break;
      }
    }

    //event addons


    /**
     * Get the event's id number
     *
     * @return int
     */
    public function getId() {
        return $this->id;
    }

    /**
     * Get the event's title
     *
     * @return string
     */
    public function getTitle()
    {
        $title = $this->getMeta('title');
        if($title) return $title;
        return $this->order->rid.' '.$this->getDisplayNameAttribute();
    }

    /**
     * Is it an all day event?
     *
     * @return bool
     */
    public function isAllDay()
    {
        if($this->getMeta('allday', null) === true || $this->getMeta('allday', null) === 'true'){
          return true;
        }else if($this->getMeta('allday', null) === false || $this->getMeta('allday', null) === 'false'){
          return false;
        }
        if(!empty($this->schedule_end)) return false;
        return true;
    }

    /**
     * Get the start time
     *
     * @return DateTime
     */
    public function getStart()
    {
        return Carbon::parse($this->schedule_at);
    }

    /**
     * Get the end time
     *
     * @return DateTime
     */
    public function getEnd()
    {
        if(!empty($this->schedule_end)) return Carbon::parse($this->schedule_end);
        return Carbon::parse($this->schedule_at);
    }

    /**
     * Optional FullCalendar.io settings for this event
     *
     * @return array
     */
    public function getEventOptions()
    {
        return [
            'color' => $this->getColor(),
            'url' => '/invoice/'.$this->order->id.'?tid='.$this->id,
            'resourceId' => $this->resource_id,
            'id' => $this->id,
            'type' => 'task',
            'company' => $this->company_code
        ];
    }
}

app/Http/Controllers/Frontend/Customers/CustomersController.php
<?php

namespace App\Http\Controllers\Frontend\Customers;

use App\Http\Requests;
use App\Http\Requests\Frontend\Customers\CreateCustomersRequest;
use App\Http\Requests\Frontend\Customers\UpdateCustomersRequest;
use App\Http\Requests\Frontend\Customers\DeleteCustomersRequest;
use App\Repositories\Frontend\Customers\CustomersRepository;
use Illuminate\Http\Request;
use Flash;
use InfyOm\Generator\Controller\AppBaseController;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class CustomersController extends AppBaseController
{
    /** @var  CustomersRepository */
    private $customersRepository;

    function __construct(CustomersRepository $customersRepo)
    {
        $this->customersRepository = $customersRepo;
    }

    /**
     * Display a listing of the Customers.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->customersRepository->pushCriteria(new RequestCriteria($request));
        $customers = $this->customersRepository->all();

        return view('frontend.customers.index')
            ->with('customers', $customers);
    }

    /**
     * Show the form for creating a new Customers.
     *
     * @return Response
     */
    public function create()
    {
        return view('frontend.customers.create');
    }

    /**
     * Store a newly created Customers in storage.
     *
     * @param CreateCustomersRequest $request
     *
     * @return Response
     */
    public function store(CreateCustomersRequest $request)
    {
        $input = $request->all();

        $customers = $this->customersRepository->create($input);

        Flash::success('Customers saved successfully.');

        return redirect(route('customers.index'));
    }

    /**
     * Display the specified Customers.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $customers = $this->customersRepository->findWithoutFail($id);

        if (empty($customers)) {
            Flash::error('Customers not found');

            return redirect(route('customers.index'));
        }

        return view('frontend.customers.show')->with('customers', $customers);
    }

    /**
     * Show the form for editing the specified Customers.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $customers = $this->customersRepository->findWithoutFail($id);

        if (empty($customers)) {
            Flash::error('Customers not found');

            return redirect(route('customers.index'));
        }

        return view('frontend.customers.edit')->with('customers', $customers);
    }

    /**
     * Update the specified Customers in storage.
     *
     * @param  int              $id
     * @param UpdateCustomersRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCustomersRequest $request)
    {
        $customers = $this->customersRepository->findWithoutFail($id);

        if (empty($customers)) {
            Flash::error('Customers not found');

            return redirect(route('customers.index'));
        }

        $customers = $this->customersRepository->update($request->all(), $id);

        Flash::success('Customers updated successfully.');

        return redirect(route('customers.index'));
    }

    /**
     * Remove the specified Customers from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id, DeleteCustomersRequest $request)
    {
        $customers = $this->customersRepository->findWithoutFail($id);

        if (empty($customers)) {
            Flash::error('Customers not found');

            return redirect(route('customers.index'));
        }

        $this->customersRepository->delete($id);

        Flash::success('Customers deleted successfully.');

        return redirect(route('customers.index'));
    }
}

app/Http/Controllers/Frontend/Customers/PhotoSelectController.php
<?php

namespace App\Http\Controllers\Frontend\Customers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Models\Companies\Company;
use App\Models\Media\Gallery;
use App\Models\Media\PhotoSelect;
use Firebase\JWT\JWT;
use App\Events\PhotoSelected;
use App\Events\NewIntelReceived;
use App\Models\Media\Photo;

class PhotoSelectController extends Controller
{

    public function phpDetailApi($id, Request $req){
      $photo = Photo::find($id);
      if(!$photo){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! no photo'
        ], 401);
      }

      $detail = json_encode($req->input('detail'));

      $photo->details = $detail;
      $photo->update();

      event(new NewIntelReceived(NewIntelReceived::TYPE_PHOTO, $detail));

      return response()->json([
          'fail' => false,
          'msg' => 'good update'
      ]);
    }

    public function apiDlKeys($id, Request $req){
       \Debugbar::disable();
      $ps = Photoselect::find($id);

      if(!$ps){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! no ps'
        ], 401);
      }

      $selectedkeys = [];
      foreach (explode(',', $ps->selected) as $photoid) {
        $photo = Photo::find($photoid);
        if($photo){
          $selected[] = [
            'id' => $photo->id,
            'thumb' => $photo->thumbnail(),
            'src'       => $photo->url()
          ];

          $selectedkeys[] = $photo->file->s3key;
        }
      }

      return json_encode($selectedkeys);
    }

    public function show($id, Request $req){
      \Debugbar::disable();
      try{
        $info = JWT::decode($id, config('app.key'), array('HS256'));
      }catch(\Exception $e){
        return abort(404);
      }

      $ps = Photoselect::find($info->psid);

      if(!$ps){
        return abort(404);
      }

      $photos = [];
      foreach ($ps->gallery->photos as $photo) {
        $photos[] = [
          'id'  => $photo->id,
          'thumb' => $photo->thumbnail(),
          'src'       => $photo->withMark($ps->company->code, $photo->makeup ? $photo->makeup->name : '', $photo->photographer ? $photo->photographer->name : ''),
          'key' => $photo->file->s3key
        ];
      }

      $selected = false;
      if($ps->status == 'selected'){
        $selected = explode(',' , $ps->selected);
      }

      //dd($selected->count());

      return view('frontend.photoselect.show')
            ->with('selected', $selected)
            ->with('id', $id)
            ->with('ps', $ps)
            ->with('photos', $photos);
    }

    public function update($id, Request $req){
      \Debugbar::disable();
      try{
        $info = JWT::decode($id, config('app.key'), array('HS256'));
      }catch(\Exception $e){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! no token'
        ], 401);
      }

      $ps = Photoselect::find($info->psid);
      if(!$ps){
          return response()->json([
              'fail' => true,
              'msg' => 'Invalid arguments! no PS'
          ], 401);
      }

      if($ps->status != 'created' && $ps->status != 'viewed'){
        return response()->json([
            'fail' => true,
            'msg' => 'Not Able to select the photo due to previous selection'
        ], 401);
      }

      if(!$req->has('selected')){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! no selected'
        ], 401);
      }

      if(count($req->input('selected')) > $ps->max_allow){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! Exceed max',
            'selected' => $req->input('selected')
        ], 401);
      }

      $select = collect($req->input('selected'));
      $ogStatus = $ps->status;

      $ps->selected = $select->implode('id', ',');
      $ps->status = 'selected';

      if($req->has('comment')){
        $ps->remark = $req->input('comment');
      }

      $ps->update();

      event(new PhotoSelected($ps, $ogStatus));

      //event ps update

      return $ps;

    }

    public function store(Request $req){
      if(!$req->has('store') || !$req->has('gid')  || !$req->has('ms')){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments!'
        ], 401);
      }

      $company = Company::find($req->input('store'));
      if(!$company){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! No Company'
        ], 401);
      }

      $gallery = Gallery::find($req->input('gid'));

      if(!$gallery){
        return response()->json([
            'fail' => true,
            'msg' => 'Invalid arguments! No Gallery'
        ], 401);
      }

      $photoselect = new PhotoSelect();

      $photoselect->user_id = $req->user()->id;
      $photoselect->gallery_id = $gallery->id;
      $photoselect->company_id = $company->id;
      $photoselect->status = 'created';
      $photoselect->max_allow = $req->input('ms');

      $photoselect->save();

      if($req->has('wm')){
        $photoselect->updateMeta('wm', 'true');
      }

      if($req->has('text')){
        $photoselect->updateMeta('text', 'true');
      }

      return $gallery->photoselects;
    }
}

resources/views/frontend/invoice/index.blade.php
@extends('frontend.layouts.master')

@section('content')
    <div class="row">

        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-home"></i> Invoices</div>

                <div class="panel-body">
                    <table class="table table-bordered table-responsive" id="invoice-table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Status</th>
                                <th>Package</th>
                                <th>Customer</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                    <!-- Indicates a successful or positive action -->

                    @permission('create-invoice-pa')
                    <a href="{!! route('invoice.create') !!}?c=1" class="btn btn-success">Create New PA Invoice</a>
                    @endauth
                    @permission('create-invoice-la')
                    <a href="{!! route('invoice.create') !!}?c=2" class="btn btn-success">Create New LA Invoice</a>
                    @endauth
                    @permission('create-invoice-ca')
                    <a href="{!! route('invoice.create') !!}?c=3" class="btn btn-success">Create New CA Invoice</a>
                    @endauth
                </div>
            </div><!-- panel -->


        </div><!-- col-md-10 -->

    </div><!-- row -->
@endsection

@section('after-scripts-end')
<script>
    $(function() {
        $('#invoice-table').DataTable({
            processing: true,
            serverSide: true,
            ajax: '{!! route('frontend.invoice.tabledata') !!}',
            columns: [
                { data: 'rid', name: 'orders.rid' },
                { data: 'status', name: 'orders.status' },
                { data: 'package.display_name', name: 'package.display_name' },
                { data: 'customer.display_name', name: 'customer.display_name' },
                {data: 'action', name: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>

@endsection

resources/views/frontend/invoice/showTask.blade.php
<br/>
<div class="panel panel-default">
    <ul class="nav nav-tabs panel-heading" role="tablist">
      @foreach($tasks as $catalog => $task)
        <li role="presentation" @if($navcatalog && $catalog == $navcatalog) class="active" @elseif (!$nav && $task == reset($tasks)) class="active"@endif><a href="#{!! seoUrl($catalog) !!}" aria-controls="{!! seoUrl($catalog) !!}" role="tab" data-toggle="tab">{!! $catalog !!} <span class="label @if ($taskCounts[$catalog] != 0) label-primary @else label-default @endif">{!! $taskCounts[$catalog] !!}</span></a></li>
      @endforeach
    </ul>
    <script>
      var tasks = [];
    </script>
    <div class="tab-content">
    @foreach($tasks as $catalog => $task)
      <div role="tabpanel" class="tab-pane @if($navcatalog && $catalog == $navcatalog) active @elseif (!$nav && $task == reset($tasks)) active @endif" id="{!! seoUrl($catalog) !!}">
      <style>
        .list-group hr{
          margin-top: 5px;
          margin-bottom: 5px;
        }
      </style>
      <ul class="list-group">
          @foreach(collect($task)->chunk(3) as $singleTasks)
          <div class="row">
            @foreach($singleTasks as $singleTask)
            <div class="col-md-4">
              <form method="POST" action="{!! route('task.post').'?tid='.$singleTask['detail']->id !!}" style="margin: 5px;" >
              {!! csrf_field() !!}
              <input id="inputStatus{!! $singleTask['detail']->id !!}" type="hidden" name="status" value="{!! $singleTask['detail']->status !!}" />
              <li class="list-group-item" @if($singleTask['nav']) style="border:2px #7d7d7d solid;" @endif>
                  <span data-type="select" class="label label-default taskStatus{!! $singleTask['detail']->id !!}" >{!! $singleTask['detail']->status !!}</span>
                  <span class="prefix"><b>{!! $singleTask['service']->display_name !!}</b></span>
                  <span class="pull-right">
                    <button type="submit" class="btn btn-success btn-xs">Update 更新</button>
                  </span>
                  <hr/>
                  @if($singleTask['detail']->allowSchedule())
{{--                   <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Schedule</span>
                    <input type="text" class="form-control taskScheduleStart{!! $singleTask['detail']->id !!}" name="daterange" value="Click to Set"/>
                  </div> --}}
                  <input id="inputScheduleStart{!! $singleTask['detail']->id !!}" type="hidden" name="schedule" value="{!! $singleTask['detail']->schedule_at !!}"/>
                  <input id="inputScheduleEnd{!! $singleTask['detail']->id !!}" type="hidden" name="scheduleEnd" value="{!! $singleTask['detail']->schedule_end !!}"/>
                  <div class="input-group">
                    <div class="form-group registration-date">
                      <div class="input-group registration-date-time" id="detailDateTime{!! $singleTask['detail']->id !!}">
                        <span class="input-group-addon" ><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></span>
                        <input class="form-control date start" name="registration_date" type="text">
                        <input class="form-control time start" name="registration_time" type="text">
                        <span class="input-group-addon" >To</span>
                        <input class="form-control date end" name="registration_time" type="text">
                        <input class="form-control time end" name="registration_time" type="text">
                      </div>
                    </div>
                  </div>
                  <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">All Day</span>
                    <input class="form-control" type="checkbox" name="allday" id="inputAllDay{!! $singleTask['detail']->id !!}" @if($singleTask['detail']->isAllDay()) checked @endif>
                  </div>
                  @endif
                  <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">Assigns</span>
                    <select class="user-select-ajax" name="assign_name[]" multiple="multiple">
                      @if( count($singleTask['detail']->assign_name) > 0 )
                      @foreach($singleTask['detail']->assign_name as $uid => $name)
                        <option value="{!! $uid !!}" selected="selected">{!! $name !!}</option>
                      @endforeach
                      @endif
                    </select>
                  </div>
                  @foreach($singleTask['detail']->options() as $option)
                    <div class="input-group">
                      <span class="input-group-addon">{{$option->name}}</span>
                      @if($option->type == 'text')
                      <input type="text" class="form-control taskOp{{$option->name}}{!! $singleTask['detail']->id !!}" name="options[{{$option->name}}]" value="{{$singleTask['options']['op-'.$option->name] or ''}}"/>
                      @elseif ($option->type == 'integer')
                      <input type="number" class="form-control taskOp{{$option->name}}{!! $singleTask['detail']->id !!}" name="options[{{$option->name}}]" value="{{$singleTask['options']['op-'.$option->name] or ''}}"/>
                      @elseif ($option->type == 'select')
                      <select class="form-control optselect taskOp{{$option->name}}{!! $singleTask['detail']->id !!}" name="options[{{$option->name}}]" >
                        @foreach($option->options as $seOption)
                        <option value="{{$seOption}}" @if(!empty($singleTask['options']['op-'.$option->name]) && $singleTask['options']['op-'.$option->name] == $seOption) selected @endif>{{$seOption}}</option>
                        @endforeach
                      </select>
                      @endif
                    </div>
                  @endforeach

                  @if($singleTask['detail']->status == 'submited' || $singleTask['detail']->status == 'pending')
                  <div class="input-group">
                    <span class="input-group-addon">Photos</span>
                    <span class="btn btn-success btn-xs" data-toggle="modal" data-target="#galleryModal{!! $singleTask['detail']->id !!}">Browse</span>
                  </div>

                  <!-- Modal -->
                  <div class="modal fade" id="galleryModal{!! $singleTask['detail']->id !!}" tabindex="-1" role="dialog" >
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <h4 class="modal-title">Photos</h4>
                        </div>
                        <div class="modal-body">
                          <div class="parent-container" id="containerGallery{!! $singleTask['detail']->id !!}">
                            @foreach($singleTask['detail']->galleryDesktop() as $photo)
                            <a class="@if($photo['selected']) picked @endif" href="{{ $photo['src'] }}"><img src="{{ $photo['thumbnail'] }}" class="gallery-photo-preview @if($photo['selected']) picked @endif"></a>
                            @endforeach
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="button" id="galleryDLALL{!! $singleTask['detail']->id !!}" class="btn btn-primary">Download All</button>
                          @if($singleTask['detail']->status == 'pending')
                          <button type="button" id="galleryDLSelected{!! $singleTask['detail']->id !!}" class="btn btn-primary">Download Selected</button>
                          @endif
                          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  @endif
                  <hr/>
                  <div class="form-group">
                    <label>Details:</label>
                    <textarea class="form-control" name="details" rows="2">{!! $singleTask['detail']->details !!}</textarea>
                  </div>
              </li>
              </form>
              <script>
                tasks.push({
                  tid : '{!! $singleTask['detail']->id !!}',
                  class: 'taskStatus{!! $singleTask['detail']->id !!}',
                  status:'{!! $singleTask['detail']->status !!}',
                  id: 'inputStatus{!! $singleTask['detail']->id !!}',
                  options: {!! $singleTask['detail']->avaible_options !!},
                  @if($singleTask['detail']->status == 'submited' || $singleTask['detail']->status == 'pending')
                  gallery: true,
                  galleryel: 'containerGallery{!! $singleTask['detail']->id !!}',
                  btnDlAll: 'galleryDLALL{!! $singleTask['detail']->id !!}',
                  @else
                  gallery: false,
                  @endif
                  @if($singleTask['detail']->status == 'pending')
                  btnDLSelected: 'galleryDLSelected{!! $singleTask['detail']->id !!}',
                  @else
                  btnDLSelected: false,
                  @endif
                  @if($singleTask['detail']->allowSchedule())
                  detail_id: 'detailDateTime{!! $singleTask['detail']->id !!}',
                  schedule_id: 'inputScheduleStart{!! $singleTask['detail']->id !!}',
                  schedule_class: 'taskScheduleStart{!! $singleTask['detail']->id !!}',
                  scheduleEnd_id: 'inputScheduleEnd{!! $singleTask['detail']->id !!}',
                  allday_id: 'inputAllDay{!! $singleTask['detail']->id !!}',
                  startDate: '{!! $singleTask['detail']->schedule_at ? $singleTask['detail']->schedule_at : 'false'!!}',
                  endDate: '{!! $singleTask['detail']->schedule_end ?  $singleTask['detail']->schedule_end : 'false' !!}',
                  schedule: true,
                  @else
                  schedule: false
                  @endif
                });
              </script>
            </div>
            @endforeach
          </div>
          @endforeach
      </ul>
    </div>
    @endforeach
    </div>
</div>